[package]
name = "matasanorust"
version = "0.1.0"
authors = ["Kevin Teh <kkwteh@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
hex-literal = "0.3.1"
lazy_static = "1.4.0"
openssl = "0.10.32"
aes = "0.6.0"
block-modes = "0.7.0"